added files for auth
ArtemHryn/petly_backend pull request #1
Opened 2023-02-13 14:13 UTC by OlyaNegrych

2023-02-13 17:46 UTC, ArtemHryn requested changes

2023-02-13 17:46 UTC, ArtemHryn commented on controllers/authControllers.js
> +const gravatar = require("gravatar");
Все це не актуальне на даний момент, видаляємо

2023-02-13 17:46 UTC, ArtemHryn commented on helper/sendMail.js
> +    text: `Please, confirm your email address http://localhost:3000/auth/verify/${verificationToken}`,
тут буде посилання на хироку

2023-02-13 17:46 UTC, ArtemHryn commented on models/userModel.js
> +
не така схема, там буде більше

2023-02-13 17:46 UTC, ArtemHryn commented on routes/api/authRouter.js
>  const express = require("express");
куча сміття і код з неба) видалити все що додала і зробити заново чистий і охайний

2023-02-13 17:46 UTC, ArtemHryn commented on services/authServices.js
> +// const sendMail = require("../helper/sendMail");
видалити

2023-02-13 17:46 UTC, ArtemHryn commented on services/authServices.js
> +// const { replaceAvatar } = require("../helpers/avatarOptions");
видалити

2023-02-13 17:46 UTC, ArtemHryn commented on services/authServices.js
> +  const avatarURL = gravatar.url(email);
у нас не буде аватара під час регістрації

2023-02-13 17:46 UTC, ArtemHryn commented on services/authServices.js
> +
все сміття видаляємо

2023-02-13 17:46 UTC, ArtemHryn commented on package.json
> +    "uuidv4": "^6.2.13"
навіщо нам uuid? у нас ід база створює

2023-02-13 20:16 UTC, OlyaNegrych commented on controllers/authControllers.js
> +const gravatar = require("gravatar");
видалила

2023-02-13 20:17 UTC, OlyaNegrych commented on helper/sendMail.js
> +    text: `Please, confirm your email address http://localhost:3000/auth/verify/${verificationToken}`,
закоментувала, чи видалити все?

2023-02-13 20:18 UTC, OlyaNegrych commented on models/userModel.js
> +
схему доповнила, внесла: email, password, name, city, phone, token (поки верифікацію не додавала)

2023-02-13 20:19 UTC, OlyaNegrych commented on routes/api/authRouter.js
>  const express = require("express");
коменти повидаляла, код коригую

2023-02-13 20:20 UTC, OlyaNegrych commented on services/authServices.js
> +// const sendMail = require("../helper/sendMail");
uuid я використовувала для верифайТокена.... але поки видалила
а jwt мені тут потрібен :)

2023-02-13 20:21 UTC, OlyaNegrych commented on services/authServices.js
> +// const { replaceAvatar } = require("../helpers/avatarOptions");
я тут використовую і помилки і юзера :)

2023-02-13 20:22 UTC, OlyaNegrych commented on services/authServices.js
> +  const avatarURL = gravatar.url(email);
видалила пункт з аватаром

2023-02-13 20:23 UTC, OlyaNegrych commented on services/authServices.js
> +
поки видалила верифікацію

2023-02-13 20:24 UTC, OlyaNegrych commented on package.json
> +    "uuidv4": "^6.2.13"
треба деінсталювати uuidv4?

2023-02-14 00:14 UTC, ArtemHryn approved these changes

2023-02-14 00:14 UTC, merged